# Generated by Django 4.2 on 2023-05-02 10:15

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_organizationunit_unique_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('slug', models.SlugField(default=uuid.UUID('094d9532-85fe-4e47-baf8-259075e61140'), unique=True)),
                ('sub_title', models.CharField(blank=True, max_length=100, null=True)),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to='cover_img')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visibility', models.ManyToManyField(to='accounts.section')),
            ],
        ),
    ]
