# Generated by Django 4.2 on 2023-05-02 10:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=uuid.UUID('173a10ba-6f71-456e-b450-285ebd779139'), unique=True),
        ),
    ]
