# Generated by Django 4.2 on 2023-05-02 10:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationunit',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('0a6f5032-3db5-48c1-afa1-14407dd06691'), editable=False, unique=True),
        ),
    ]
