# Generated by Django 4.2 on 2023-04-24 10:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_groups_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Section',
        ),
        migrations.RenameField(
            model_name='organizationmember',
            old_name='group',
            new_name='section',
        ),
        migrations.AlterField(
            model_name='organizationunit',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('7473f25f-97b8-42e4-9148-4620b051b885'), editable=False, unique=True),
        ),
    ]
