# Generated by Django 4.2 on 2023-05-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_organizationunit_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationunit',
            name='unique_id',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
