# Generated by Django 4.2 on 2023-04-28 11:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_user_alter_organizationunit_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationunit',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('6de6e1fd-9688-4ec3-a19d-e05b9d0e681e'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('organization', 'name')},
        ),
    ]
