# Generated by Django 4.2 on 2023-04-28 17:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_organizationunit_unique_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='organizationunit',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('b4d60af7-3751-4042-9791-914415504ac5'), editable=False, unique=True),
        ),
    ]
